"""split_color_standards

Revision ID: 00004
Revises: 00003
Create Date: 2026-09-18 16:04:11.122120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00004'
down_revision: Union[str, None] = '00003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('color_primaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('color_spaces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('color_transfers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    naming_convention = {
        "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    }
    with op.batch_alter_table('color', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.drop_constraint('fk_color_color_primaries_id_color_standards', type_='foreignkey')
        batch_op.drop_constraint('fk_color_color_trc_id_color_standards', type_='foreignkey')
        batch_op.drop_constraint('fk_color_colorspace_id_color_standards', type_='foreignkey')
        batch_op.create_foreign_key('fk_color_color_primaries_id_color_primaries', 'color_primaries', ['color_primaries_id'], ['id'])
        batch_op.create_foreign_key('fk_color_color_trc_id_color_transfers', 'color_transfers', ['color_trc_id'], ['id'])
        batch_op.create_foreign_key('fk_color_colorspace_id_color_spaces', 'color_spaces', ['colorspace_id'], ['id'])

    op.drop_table('color_standards')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('color_standards',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    naming_convention = {
        "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    }
    with op.batch_alter_table('color', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.drop_constraint('fk_color_color_primaries_id_color_primaries', type_='foreignkey')
        batch_op.drop_constraint('fk_color_color_trc_id_color_transfers', type_='foreignkey')
        batch_op.drop_constraint('fk_color_colorspace_id_color_spaces', type_='foreignkey')
        batch_op.create_foreign_key('fk_color_color_primaries_id_color_standards', 'color_standards', ['color_primaries_id'], ['id'])
        batch_op.create_foreign_key('fk_color_color_trc_id_color_standards', 'color_standards', ['color_trc_id'], ['id'])
        batch_op.create_foreign_key('fk_color_colorspace_id_color_standards', 'color_standards', ['colorspace_id'], ['id'])

    op.drop_table('color_transfers')
    op.drop_table('color_spaces')
    op.drop_table('color_primaries')
    # ### end Alembic commands ###
