"""initial_schema

Revision ID: 00001
Revises: 
Create Date: 2026-09-05 21:03:03.812801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('color_ranges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('color_standards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cpu',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cpu_name', sa.String(), nullable=False),
    sa.Column('cpu_threads', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('display',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('width_px', sa.Integer(), nullable=False),
    sa.Column('height_px', sa.Integer(), nullable=False),
    sa.Column('display_aspect_ratio', sa.String(), nullable=False),
    sa.Column('pixel_aspect_ratio', sa.String(), nullable=False),
    sa.Column('pixel_format', sa.String(), nullable=False),
    sa.Column('chroma_sample_location', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('encoding',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codec', sa.String(), nullable=False),
    sa.Column('preset', sa.String(), nullable=True),
    sa.Column('encoder', sa.String(), nullable=True),
    sa.Column('average_bitrate_kilobits_per_second', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('environment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firefly_version', sa.String(), nullable=False),
    sa.Column('ffmpeg_version', sa.String(), nullable=False),
    sa.Column('compression_engine_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('absolute_path', sa.String(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hdr_format',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iteration_stages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_stages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('frames_counted', sa.Integer(), nullable=True),
    sa.Column('avg_frame_rate', sa.String(), nullable=True),
    sa.Column('r_frame_rate', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schema',
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('version')
    )
    op.create_table('segment_statuses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('color',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hdr_format_id', sa.Integer(), nullable=True),
    sa.Column('color_primaries_id', sa.Integer(), nullable=True),
    sa.Column('color_trc_id', sa.Integer(), nullable=True),
    sa.Column('colorspace_id', sa.Integer(), nullable=True),
    sa.Column('color_range_id', sa.Integer(), nullable=True),
    sa.Column('max_cll', sa.String(), nullable=True),
    sa.Column('master_display', sa.String(), nullable=True),
    sa.Column('dovi_profile', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['color_primaries_id'], ['color_standards.id'], ),
    sa.ForeignKeyConstraint(['color_range_id'], ['color_ranges.id'], ),
    sa.ForeignKeyConstraint(['color_trc_id'], ['color_standards.id'], ),
    sa.ForeignKeyConstraint(['colorspace_id'], ['color_standards.id'], ),
    sa.ForeignKeyConstraint(['hdr_format_id'], ['hdr_format.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('embedded_metadata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('encodes_count', sa.Integer(), nullable=False),
    sa.Column('last_encode_datetime_utc', sa.DateTime(), nullable=False),
    sa.Column('source_video_sha256_hash', sa.String(), nullable=False),
    sa.Column('environment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('execution_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ffmpeg_command_used', sa.String(), nullable=False),
    sa.Column('finished_datetime_utc', sa.DateTime(), nullable=False),
    sa.Column('encoding_wall_time_seconds', sa.Float(), nullable=False),
    sa.Column('evaluation_wall_time_seconds', sa.Float(), nullable=True),
    sa.Column('encoding_cpu_time_seconds', sa.Float(), nullable=True),
    sa.Column('evaluation_cpu_time_seconds', sa.Float(), nullable=True),
    sa.Column('total_wall_time_seconds', sa.Float(), nullable=True),
    sa.Column('total_cpu_time_seconds', sa.Float(), nullable=True),
    sa.Column('encoding_cpu_threads_used', sa.Integer(), nullable=False),
    sa.Column('evaluation_cpu_threads_used', sa.Integer(), nullable=True),
    sa.Column('encoding_cpu_id', sa.Integer(), nullable=False),
    sa.Column('evaluation_cpu_id', sa.Integer(), nullable=True),
    sa.Column('is_legacy_import', sa.Boolean(), nullable=False),
    sa.CheckConstraint('is_legacy_import = 1 OR encoding_cpu_time_seconds IS NOT NULL', name='chk_cpu_time'),
    sa.ForeignKeyConstraint(['encoding_cpu_id'], ['cpu.id'], ),
    sa.ForeignKeyConstraint(['evaluation_cpu_id'], ['cpu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('display_id', sa.Integer(), nullable=True),
    sa.Column('playback_id', sa.Integer(), nullable=True),
    sa.Column('encoding_id', sa.Integer(), nullable=True),
    sa.Column('color_id', sa.Integer(), nullable=True),
    sa.Column('embedded_metadata_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['color_id'], ['color.id'], ),
    sa.ForeignKeyConstraint(['display_id'], ['display.id'], ),
    sa.ForeignKeyConstraint(['embedded_metadata_id'], ['embedded_metadata.id'], ),
    sa.ForeignKeyConstraint(['encoding_id'], ['encoding.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ),
    sa.ForeignKeyConstraint(['playback_id'], ['playback.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_video_id', sa.Integer(), nullable=False),
    sa.Column('output_video_id', sa.Integer(), nullable=True),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('created_datetime_utc', sa.DateTime(), nullable=False),
    sa.Column('is_legacy_import', sa.Boolean(), nullable=False),
    sa.Column('total_time_seconds', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['output_video_id'], ['video.id'], ),
    sa.ForeignKeyConstraint(['source_video_id'], ['video.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['job_stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('segments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('from_frame', sa.Integer(), nullable=False),
    sa.Column('to_frame', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('total_time_seconds', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['segment_statuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iteration',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('environment_id', sa.Integer(), nullable=False),
    sa.Column('execution_data_id', sa.Integer(), nullable=False),
    sa.Column('crf', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environment.id'], ),
    sa.ForeignKeyConstraint(['execution_data_id'], ['execution_data.id'], ),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['iteration_stages.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('iteration_id', sa.Integer(), nullable=False),
    sa.Column('metric_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['iteration_id'], ['iteration.id'], ),
    sa.ForeignKeyConstraint(['metric_id'], ['evaluation_metrics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluation')
    op.drop_table('iteration')
    op.drop_table('segments')
    op.drop_table('job')
    op.drop_table('video')
    op.drop_table('execution_data')
    op.drop_table('embedded_metadata')
    op.drop_table('color')
    op.drop_table('segment_statuses')
    op.drop_table('schema')
    op.drop_table('playback')
    op.drop_table('job_stages')
    op.drop_table('iteration_stages')
    op.drop_table('hdr_format')
    op.drop_table('file')
    op.drop_table('evaluation_metrics')
    op.drop_table('environment')
    op.drop_table('encoding')
    op.drop_table('display')
    op.drop_table('cpu')
    op.drop_table('color_standards')
    op.drop_table('color_ranges')
    # ### end Alembic commands ###
